# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RAHUL VARMA
email: rahulv2504@gmail.com
description: "Rahul Varma is a Student, Web Developer, Learner"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rahulvarma.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  rahvar

# Build settings
markdown: kramdown
